FROM node:20-alpine

WORKDIR /app

ENV PORT=7860
EXPOSE 7860

COPY frontend/package.json frontend/pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY frontend/ ./
RUN pnpm build

CMD ["node_modules/.bin/next", "start", "-p", "7860"]
